###################################################################

# Created by write_sdc on Mon Feb 13 05:33:04 2017

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_load -pin_load 0.01 [get_ports {col_out[31]}]
set_load -pin_load 0.01 [get_ports {col_out[30]}]
set_load -pin_load 0.01 [get_ports {col_out[29]}]
set_load -pin_load 0.01 [get_ports {col_out[28]}]
set_load -pin_load 0.01 [get_ports {col_out[27]}]
set_load -pin_load 0.01 [get_ports {col_out[26]}]
set_load -pin_load 0.01 [get_ports {col_out[25]}]
set_load -pin_load 0.01 [get_ports {col_out[24]}]
set_load -pin_load 0.01 [get_ports {col_out[23]}]
set_load -pin_load 0.01 [get_ports {col_out[22]}]
set_load -pin_load 0.01 [get_ports {col_out[21]}]
set_load -pin_load 0.01 [get_ports {col_out[20]}]
set_load -pin_load 0.01 [get_ports {col_out[19]}]
set_load -pin_load 0.01 [get_ports {col_out[18]}]
set_load -pin_load 0.01 [get_ports {col_out[17]}]
set_load -pin_load 0.01 [get_ports {col_out[16]}]
set_load -pin_load 0.01 [get_ports {col_out[15]}]
set_load -pin_load 0.01 [get_ports {col_out[14]}]
set_load -pin_load 0.01 [get_ports {col_out[13]}]
set_load -pin_load 0.01 [get_ports {col_out[12]}]
set_load -pin_load 0.01 [get_ports {col_out[11]}]
set_load -pin_load 0.01 [get_ports {col_out[10]}]
set_load -pin_load 0.01 [get_ports {col_out[9]}]
set_load -pin_load 0.01 [get_ports {col_out[8]}]
set_load -pin_load 0.01 [get_ports {col_out[7]}]
set_load -pin_load 0.01 [get_ports {col_out[6]}]
set_load -pin_load 0.01 [get_ports {col_out[5]}]
set_load -pin_load 0.01 [get_ports {col_out[4]}]
set_load -pin_load 0.01 [get_ports {col_out[3]}]
set_load -pin_load 0.01 [get_ports {col_out[2]}]
set_load -pin_load 0.01 [get_ports {col_out[1]}]
set_load -pin_load 0.01 [get_ports {col_out[0]}]
set_load -pin_load 0.01 [get_ports {key_out[31]}]
set_load -pin_load 0.01 [get_ports {key_out[30]}]
set_load -pin_load 0.01 [get_ports {key_out[29]}]
set_load -pin_load 0.01 [get_ports {key_out[28]}]
set_load -pin_load 0.01 [get_ports {key_out[27]}]
set_load -pin_load 0.01 [get_ports {key_out[26]}]
set_load -pin_load 0.01 [get_ports {key_out[25]}]
set_load -pin_load 0.01 [get_ports {key_out[24]}]
set_load -pin_load 0.01 [get_ports {key_out[23]}]
set_load -pin_load 0.01 [get_ports {key_out[22]}]
set_load -pin_load 0.01 [get_ports {key_out[21]}]
set_load -pin_load 0.01 [get_ports {key_out[20]}]
set_load -pin_load 0.01 [get_ports {key_out[19]}]
set_load -pin_load 0.01 [get_ports {key_out[18]}]
set_load -pin_load 0.01 [get_ports {key_out[17]}]
set_load -pin_load 0.01 [get_ports {key_out[16]}]
set_load -pin_load 0.01 [get_ports {key_out[15]}]
set_load -pin_load 0.01 [get_ports {key_out[14]}]
set_load -pin_load 0.01 [get_ports {key_out[13]}]
set_load -pin_load 0.01 [get_ports {key_out[12]}]
set_load -pin_load 0.01 [get_ports {key_out[11]}]
set_load -pin_load 0.01 [get_ports {key_out[10]}]
set_load -pin_load 0.01 [get_ports {key_out[9]}]
set_load -pin_load 0.01 [get_ports {key_out[8]}]
set_load -pin_load 0.01 [get_ports {key_out[7]}]
set_load -pin_load 0.01 [get_ports {key_out[6]}]
set_load -pin_load 0.01 [get_ports {key_out[5]}]
set_load -pin_load 0.01 [get_ports {key_out[4]}]
set_load -pin_load 0.01 [get_ports {key_out[3]}]
set_load -pin_load 0.01 [get_ports {key_out[2]}]
set_load -pin_load 0.01 [get_ports {key_out[1]}]
set_load -pin_load 0.01 [get_ports {key_out[0]}]
set_load -pin_load 0.01 [get_ports {iv_out[31]}]
set_load -pin_load 0.01 [get_ports {iv_out[30]}]
set_load -pin_load 0.01 [get_ports {iv_out[29]}]
set_load -pin_load 0.01 [get_ports {iv_out[28]}]
set_load -pin_load 0.01 [get_ports {iv_out[27]}]
set_load -pin_load 0.01 [get_ports {iv_out[26]}]
set_load -pin_load 0.01 [get_ports {iv_out[25]}]
set_load -pin_load 0.01 [get_ports {iv_out[24]}]
set_load -pin_load 0.01 [get_ports {iv_out[23]}]
set_load -pin_load 0.01 [get_ports {iv_out[22]}]
set_load -pin_load 0.01 [get_ports {iv_out[21]}]
set_load -pin_load 0.01 [get_ports {iv_out[20]}]
set_load -pin_load 0.01 [get_ports {iv_out[19]}]
set_load -pin_load 0.01 [get_ports {iv_out[18]}]
set_load -pin_load 0.01 [get_ports {iv_out[17]}]
set_load -pin_load 0.01 [get_ports {iv_out[16]}]
set_load -pin_load 0.01 [get_ports {iv_out[15]}]
set_load -pin_load 0.01 [get_ports {iv_out[14]}]
set_load -pin_load 0.01 [get_ports {iv_out[13]}]
set_load -pin_load 0.01 [get_ports {iv_out[12]}]
set_load -pin_load 0.01 [get_ports {iv_out[11]}]
set_load -pin_load 0.01 [get_ports {iv_out[10]}]
set_load -pin_load 0.01 [get_ports {iv_out[9]}]
set_load -pin_load 0.01 [get_ports {iv_out[8]}]
set_load -pin_load 0.01 [get_ports {iv_out[7]}]
set_load -pin_load 0.01 [get_ports {iv_out[6]}]
set_load -pin_load 0.01 [get_ports {iv_out[5]}]
set_load -pin_load 0.01 [get_ports {iv_out[4]}]
set_load -pin_load 0.01 [get_ports {iv_out[3]}]
set_load -pin_load 0.01 [get_ports {iv_out[2]}]
set_load -pin_load 0.01 [get_ports {iv_out[1]}]
set_load -pin_load 0.01 [get_ports {iv_out[0]}]
set_load -pin_load 0.01 [get_ports end_aes]
create_clock [get_ports CLK]  -period 5  -waveform {0 2.5}
set_drive 1  [get_ports {bus_in[31]}]
set_drive 1  [get_ports {bus_in[30]}]
set_drive 1  [get_ports {bus_in[29]}]
set_drive 1  [get_ports {bus_in[28]}]
set_drive 1  [get_ports {bus_in[27]}]
set_drive 1  [get_ports {bus_in[26]}]
set_drive 1  [get_ports {bus_in[25]}]
set_drive 1  [get_ports {bus_in[24]}]
set_drive 1  [get_ports {bus_in[23]}]
set_drive 1  [get_ports {bus_in[22]}]
set_drive 1  [get_ports {bus_in[21]}]
set_drive 1  [get_ports {bus_in[20]}]
set_drive 1  [get_ports {bus_in[19]}]
set_drive 1  [get_ports {bus_in[18]}]
set_drive 1  [get_ports {bus_in[17]}]
set_drive 1  [get_ports {bus_in[16]}]
set_drive 1  [get_ports {bus_in[15]}]
set_drive 1  [get_ports {bus_in[14]}]
set_drive 1  [get_ports {bus_in[13]}]
set_drive 1  [get_ports {bus_in[12]}]
set_drive 1  [get_ports {bus_in[11]}]
set_drive 1  [get_ports {bus_in[10]}]
set_drive 1  [get_ports {bus_in[9]}]
set_drive 1  [get_ports {bus_in[8]}]
set_drive 1  [get_ports {bus_in[7]}]
set_drive 1  [get_ports {bus_in[6]}]
set_drive 1  [get_ports {bus_in[5]}]
set_drive 1  [get_ports {bus_in[4]}]
set_drive 1  [get_ports {bus_in[3]}]
set_drive 1  [get_ports {bus_in[2]}]
set_drive 1  [get_ports {bus_in[1]}]
set_drive 1  [get_ports {bus_in[0]}]
set_drive 1  [get_ports {iv_en[3]}]
set_drive 1  [get_ports {iv_en[2]}]
set_drive 1  [get_ports {iv_en[1]}]
set_drive 1  [get_ports {iv_en[0]}]
set_drive 1  [get_ports {iv_sel_rd[3]}]
set_drive 1  [get_ports {iv_sel_rd[2]}]
set_drive 1  [get_ports {iv_sel_rd[1]}]
set_drive 1  [get_ports {iv_sel_rd[0]}]
set_drive 1  [get_ports {key_en[3]}]
set_drive 1  [get_ports {key_en[2]}]
set_drive 1  [get_ports {key_en[1]}]
set_drive 1  [get_ports {key_en[0]}]
set_drive 1  [get_ports {key_sel_rd[1]}]
set_drive 1  [get_ports {key_sel_rd[0]}]
set_drive 1  [get_ports {data_type[1]}]
set_drive 1  [get_ports {data_type[0]}]
set_drive 1  [get_ports {addr[1]}]
set_drive 1  [get_ports {addr[0]}]
set_drive 1  [get_ports {op_mode[1]}]
set_drive 1  [get_ports {op_mode[0]}]
set_drive 1  [get_ports {aes_mode[1]}]
set_drive 1  [get_ports {aes_mode[0]}]
set_drive 1  [get_ports start]
set_drive 1  [get_ports disable_core]
set_drive 1  [get_ports write_en]
set_drive 1  [get_ports read_en]
set_drive 1  [get_ports first_block]
set_drive 1  [get_ports rst_n]
set_drive 1  [get_ports CLK]
